ALTER TABLE orders
ADD COLUMN order_number TEXT UNIQUE,
ADD COLUMN subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN shipping_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN tax_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE order_items
ADD COLUMN total_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00;
